<a href="https://colab.research.google.com/github/YujinCHACHA/-project-FOI_KHN/blob/main/2_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install fast_ml

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting fast_ml
  Downloading fast_ml-3.68-py3-none-any.whl (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.1/42.1 KB 2.3 MB/s eta 0:00:00
Installing collected packages: fast_ml
Successfully installed fast_ml-3.68

In [ ]:
from fast_ml.model_development import train_valid_test_split

In [ ]:
# 데이터 프레임 생성을 위한 라이브러리
import pandas as pd

# 시각화를 위한 라이브러리
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
plt.rcParams['font.size'] = 15
plt.style.use('ggplot')
plt.rc('font', family='NanumGothic')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/FOI_KHN/data_scaled_final.csv')

In [ ]:
data = data.drop(columns = ['Unnamed: 0'])

In [ ]:
y_data = data[['고혈압 의사진단 여부(부)','고혈압 의사진단 여부(모)','고지혈증 의사진단 여부(부)','고지혈증 의사진단 여부(모)','허혈성심장질환 의사진단 여부(부)','허혈성심장질환 의사진단 여부(모)','뇌졸중 의사진단 여부(부)','뇌졸중 의사진단 여부(모)','당뇨병 의사진단 여부(부)','당뇨병 의사진단 여부(모)']]

In [ ]:
y_data = data[['고혈압 의사진단 여부(부)','고혈압 의사진단 여부(모)','고혈압 의사진단 여부(형제자매)',
               '고지혈증 의사진단 여부(부)','고지혈증 의사진단 여부(모)','고지혈증 의사진단 여부(형제자매)',
               '허혈성심장질환 의사진단 여부(부)','허혈성심장질환 의사진단 여부(모)','허혈성심장질환 의사진단 여부(형제자매)',
               '뇌졸중 의사진단 여부(부)','뇌졸중 의사진단 여부(모)','뇌졸중 의사진단 여부(형제자매)','당뇨병 의사진단 여부(부)',
               '당뇨병 의사진단 여부(모)','당뇨병 의사진단 여부(형제자매)']]
y_list = y_data.columns

In [ ]:
num_data = data[['주당 평균 근로시간', '최종 수축기 혈압(2,3차 평균)', '최종 이완기 혈압(2,3차 평균)', '신장', '체중',
       '허리둘레', '체질량지수', '공복혈당', '당화혈색소', '총콜레스테롤', 'HDL-콜레스테롤(보정값)', '중성지방',
       'AST(SGOT)', 'ALT(SGPT)', '헤모글로빈', '헤마토크리트', '혈중요소질소', '혈중크레아티닌', '백혈구',
       '적혈구', '혈소판', '요크레아티닌', '식품섭취량', '에너지', '수분', '단백질', '지방', '탄수화물', '칼슘',
       '인', '철', '나트륨', '칼륨', '베타카로틴', '레티놀', '티아민', '리보플라빈', '나이아신', '비타민C',
       '요단백']]
num_list = num_data.columns

In [ ]:
to_drop = y_list.append(num_list)

In [ ]:
nom_data = data.drop(columns = to_drop)
nom_list = nom_data.columns

In [ ]:
y_corr = data.corr()[y_list]

# 상관계수 분석: 0.05이상인 애들을 x로 갖다쓰려고(가족력 제외)

- 양의 상관계수:['교육수준 재분류 코드','교육수준: 학력','(성인) 유년기환경: 아버지 교육수준','(성인) 유년기환경: 어머니 교육수준','고혈압 의사진단 여부(형제자매)','소득 5분위수(가구)','가구 세대구성코드_4','소득 4분위수(가구)','가구원수','지방','최종 이완기 혈압(2,3차 평균)','직업재분류 및 실업/비경제활동 상태 코드_1','(만12세이상) 한 번에 마시는 음주량']
- 음의 상관계수:['만나이','가구 세대구성코드_2','기혼|사별','결혼상태','혈중요소질소','직업재분류 및 실업/비경제활동 상태 코드_4','가구 세대구성코드_1']

In [ ]:
y_corr.sort_values(by='고혈압 의사진단 여부(부)',axis=0,ascending=False).iloc[10:21,:]  # top 20까지 썼다.

,고혈압 의사진단 여부(부),고혈압 의사진단 여부(모),고혈압 의사진단 여부(형제자매),고지혈증 의사진단 여부(부),고지혈증 의사진단 여부(모),고지혈증 의사진단 여부(형제자매),허혈성심장질환 의사진단 여부(부),허혈성심장질환 의사진단 여부(모),허혈성심장질환 의사진단 여부(형제자매),뇌졸중 의사진단 여부(부),뇌졸중 의사진단 여부(모),뇌졸중 의사진단 여부(형제자매),당뇨병 의사진단 여부(부),당뇨병 의사진단 여부(모),당뇨병 의사진단 여부(형제자매)
허혈성심장질환 의사진단 여부(부),0.104062,0.037496,0.000591,0.108801,0.043066,0.022189,1.000000,0.045149,0.032552,0.004103,0.003146,-0.008571,0.067399,0.018954,-0.003944
소득 5분위수(가구),0.102686,0.091972,-0.035820,0.040972,0.075569,0.023719,0.056717,0.035668,-0.004769,-0.004182,-0.016394,-0.029577,0.081490,0.060578,-0.044783
가구 세대구성코드_4,0.100564,0.059518,-0.079704,0.052224,0.057329,-0.001917,0.042789,0.016331,-0.014386,-0.013052,-0.044803,-0.035874,0.089752,0.052267,-0.071614
소득 4분위수(가구),0.100508,0.087249,-0.041129,0.038832,0.070471,0.022895,0.060521,0.036840,0.000875,0.000692,-0.017691,-0.027372,0.077650,0.058007,-0.046839
가구원수,0.086387,0.067386,-0.076627,0.042784,0.058117,-0.002007,0.039941,0.013424,-0.010900,-0.007406,-0.037059,-0.033842,0.085502,0.053299,-0.063534
고지혈증 의사진단 여부(모),0.077859,0.146195,0.007786,0.154068,1.000000,0.072604,0.043066,0.076463,-0.002448,0.004713,0.026379,-0.013874,0.050680,0.090561,-0.013317
지방,0.077140,0.038498,-0.051144,0.034399,0.039226,-0.008444,0.035248,0.003740,-0.022761,-0.010290,-0.032841,-0.033469,0.066707,0.036617,-0.050546
"최종 이완기 혈압(2,3차 평균)",0.076073,0.090495,0.058670,0.005982,-0.005043,0.010513,0.023666,0.023077,0.009538,0.021654,0.012038,0.004821,0.018426,0.013118,-0.020441
직업재분류 및 실업/비경제활동 상태 코드_1,0.070345,0.031480,-0.055214,0.043677,0.067308,-0.016326,0.060069,0.005363,-0.028499,0.003665,-0.020207,-0.028672,0.066235,0.033764,-0.048018
(만12세이상) 한 번에 마시는 음주량,0.066601,0.016073,-0.061806,0.019601,0.017895,-0.024693,0.019168,0.001074,-0.026501,0.003267,-0.026389,-0.040430,0.059329,0.024848,-0.053865
신장,0.064422,-0.000540,-0.108708,0.035533,0.022069,-0.046783,0.039561,-0.001112,-0.045232,-0.017613,-0.044283,-0.062950,0.066035,0.024456,-0.084331

In [ ]:
y_corr.sort_values(by='고혈압 의사진단 여부(부)',axis=0,ascending=True).iloc[0:10,:]  # top 20까지 썼다.

,고혈압 의사진단 여부(부),고혈압 의사진단 여부(모),고혈압 의사진단 여부(형제자매),고지혈증 의사진단 여부(부),고지혈증 의사진단 여부(모),고지혈증 의사진단 여부(형제자매),허혈성심장질환 의사진단 여부(부),허혈성심장질환 의사진단 여부(모),허혈성심장질환 의사진단 여부(형제자매),뇌졸중 의사진단 여부(부),뇌졸중 의사진단 여부(모),뇌졸중 의사진단 여부(형제자매),당뇨병 의사진단 여부(부),당뇨병 의사진단 여부(모),당뇨병 의사진단 여부(형제자매)
만나이,-0.174887,-0.121171,0.157143,-0.101856,-0.136673,0.029701,-0.084587,-0.018733,0.064441,0.033011,0.078140,0.095380,-0.175051,-0.093245,0.130741
가구 세대구성코드_2,-0.076872,-0.069584,0.066294,-0.041466,-0.062071,0.007060,-0.039467,-0.004909,0.017837,0.005570,0.032922,0.039575,-0.077068,-0.052422,0.052240
기혼|사별,-0.072011,-0.064897,0.053207,-0.036265,-0.050303,-0.004684,-0.037180,-0.016745,0.018732,-0.000584,0.018420,0.032492,-0.062879,-0.050598,0.053019
결혼상태,-0.063658,-0.028729,0.080718,-0.044464,-0.059039,0.016832,-0.030627,-0.005658,0.035516,0.016338,0.038744,0.040259,-0.059466,-0.018905,0.062031
혈중요소질소,-0.057772,-0.043328,0.076167,-0.037719,-0.066256,0.004327,-0.028660,-0.004349,0.020059,0.018887,0.036400,0.037121,-0.064116,-0.030448,0.063310
직업재분류 및 실업/비경제활동 상태 코드_4,-0.051506,-0.041651,0.014018,-0.022850,-0.031211,-0.000047,-0.020075,-0.010124,0.002603,-0.006157,0.016229,0.012580,-0.045116,-0.037922,0.010652
가구 세대구성코드_1,-0.050994,-0.043961,0.030143,-0.013545,-0.029421,-0.017130,-0.020468,-0.013520,-0.005669,0.001129,0.014362,0.006774,-0.031847,-0.033425,0.030948
동/읍면 구분_2,-0.047600,-0.029804,0.012905,-0.023058,-0.021486,-0.006702,-0.022117,-0.006787,-0.004069,0.001226,0.022021,0.020468,-0.036147,-0.034449,0.014787
직업재분류 및 실업/비경제활동 상태 코드_6,-0.041628,-0.012915,0.023702,-0.020507,-0.036843,-0.001552,-0.020115,-0.016800,0.007901,0.002832,0.003680,0.017239,-0.034689,-0.018482,0.015371
당화혈색소,-0.041230,-0.046803,0.045215,-0.025459,-0.051639,-0.001411,-0.028997,-0.004886,0.006006,0.021189,0.029998,0.018334,0.031655,0.072488,0.154471

# Data Imbalance 확인
- 1:10 매우 심함
- 1:7 다소 심함
- 1:4 양호함

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/FOI_KHN/data_scaled_final.csv')

In [ ]:
X = data[['교육수준 재분류 코드','교육수준: 학력', '(성인) 유년기환경: 아버지 교육수준', '(성인) 유년기환경: 어머니 교육수준', '소득 5분위수(가구)', '가구 세대구성코드_4', '소득 4분위수(가구)']]
Y = data['고혈압 의사진단 여부(부)']

In [ ]:
X_train, y_train, X_valid, y_valid, X_test, y_test = train_valid_test_split(data, target = '고혈압 의사진단 여부(부)', 
                                                                            train_size=0.8, valid_size=0.1, test_size=0.1)

In [ ]:
temp = y_train.index

In [ ]:
temp1 = y_train.values

In [ ]:
ydf = pd.DataFrame({'index':temp, 'values':temp1})

In [ ]:
# importing packages

import numpy as np

import pandas as pd



import matplotlib.pyplot as plt

import seaborn as sns

plt.rcParams['figure.figsize'] = [10, 6]

In [ ]:
# Summary Statistics
y_train_ = ydf.groupby('values').count()
y_train_

        index
values
0.0      2233
1.0       519

In [ ]:
temp = y_valid.index
temp1 = y_valid.values

ydf = pd.DataFrame({'index':temp, 'values':temp1})

In [ ]:
y_valid_ = ydf.groupby('values').count()
y_valid_

        index
values
0.0      2233
1.0       519

In [ ]:
temp = y_test.index
temp1 = y_test.values

ydf = pd.DataFrame({'index':temp, 'values':temp1})
y_test_ = ydf.groupby('values').count()
y_test_

        index
values
0.0      2233
1.0       519

대략 0과 1의 비율이 4:1정도 되므로 data는 균형잡혀있다.